### ISSUE TITLE
Webpack 4 issue

### ISSUE THREAD

**Issue by alapinsk** [Maarten88/rrod#12]
There is an issue with aspnet-webpack for this project. 
I get following error when I run **dotnet run** in Webapp folder,
right after it successfully connects to silo host.
`Microsoft.AspNetCore.NodeServices[0]
      (node:6608) DeprecationWarning: Tapable.plugin is deprecated. Use new API on .hooks instead`

Stack trace: 
`Shared (\rrod\src\Webapp\node_modules\webpack-dev-middleware\lib\Shared.js:233:19)
          at module.exports (\rrod\src\Webapp\node_modules\webpack-dev-middleware\middleware.js:22:15)
          at attachWebpackDevMiddleware (\rrod\src\Webapp\node_modules\aspnet-webpack\WebpackDevMiddleware.js:69:46)
          at \rrod\src\Webapp\node_modules\aspnet-webpack\WebpackDevMiddleware.js:248:21
          at Array.forEach (<anonymous>)
          at Server.<anonymous> (\rrod\src\Webapp\node_modules\aspnet-webpack\WebpackDevMiddleware.js:211:32)
          at Object.onceWrapper (events.js:313:30)
          at emitNone (events.js:106:13)
          at Server.emit (events.js:208:7)
          at emitListeningNT (net.js:1394:10)
          at _combinedTickCallback (internal/process/next_tick.js:135:11)
          at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by Maarten88** [comment]
I am not really sure why you get that error, I can't reproduce this. I do get the DeprecationWarning too, but it's just a warning, it works fine.

I upgraded webpack, webpack-dev-middleware and several other javascript dependencies to see if maybe the problem comes from a newer version of something. I removed my node_modules and reinstalled using npm install, but I still could not reproduce your error.

I have pushed my upgraded version. Could you pull this, and in the src/Webapp folder, run `npm install` (or `yarn install`), then manually run `webpack` to see if webpack can compile outside the aspnetcore javascript services middleware?
