### ISSUE TITLE
Error building silo host: The requested address is not valid in its context

### ISSUE THREAD

**Issue by vercru** [Maarten88/rrod#13]
Hi, after following the pointers in the 'Run it yourself' part of the readme I get the following exception when trying to run OrleansHost:
```
warn: Orleans.Runtime.NoOpHostEnvironmentStatistics[100708]
      No implementation of IHostEnvironmentStatistics was found. Load shedding will not work yet
Error building silo host: The requested address is not valid in its context

Unhandled Exception: System.Net.Sockets.SocketException: The requested address is not valid in its context
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Orleans.Runtime.SocketManager.GetAcceptingSocketForEndpoint(IPEndPoint address)
   at Orleans.Runtime.Messaging.IncomingMessageAcceptor..ctor(MessageCenter msgCtr, IPEndPoint here, SocketDirection socketDirection, MessageFactory messageFactory, SerializationManager serializationManager, ExecutorService executorService, ILoggerFactory loggerFactory)
   at Orleans.Runtime.Messaging.MessageCenter.Initialize(IOptions`1 endpointOptions, IOptions`1 messagingOptions, IOptions`1 networkingOptions)
   at Orleans.Runtime.Messaging.MessageCenter..ctor(ILocalSiloDetails siloDetails, IOptions`1 endpointOptions, IOptions`1 messagingOptions, IOptions`1 networkingOptions, SerializationManager serializationManager, MessageFactory messageFactory, Factory`2 gatewayFactory, ExecutorService executorService, ILoggerFactory loggerFactory)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Orleans.Runtime.Silo..ctor(ILocalSiloDetails siloDetails, IServiceProvider services)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at OrleansHost.Program.<Main>d__1.MoveNext() in D:\dev\Maarten88\rrod\src\OrleansHost\Program.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrleansHost.Program.<Main>(String[] args)
```

I'm running the azure storage emulator, with status output:
```
Windows Azure Storage Emulator 5.4.0.0 command line tool
IsRunning: True
BlobEndpoint: http://127.0.0.1:10000/
QueueEndpoint: http://127.0.0.1:10001/
TableEndpoint: http://127.0.0.1:10002/
```

**Comment by Maarten88** [comment]
I re-tested on a clean machine and it starts without problems here, even without Administrator permission.

When OrleansHost starts it will listen, by default, on ports 11111 and 30000 and resolve a default IP address. This is hardcoded in Program.cs:

    .ConfigureEndpoints(siloPort: 11111, gatewayPort: 30000)

Something must be using these ports on your machine, or something is wrong with the IP address Orleans takes by default. You can try to find what is blocking it, or change the values (make sure to also update Webapp correspondingly later). The ConfigureEndpoints() method has two more optional parameters (`addressFamily` and `listenOnAnyHostAddress`), maybe you could try try specifying a non-default value to make it work on your machine.

**Comment by vercru** [comment]
Yeah, my machine seems messed up. I can get the host to run on a different machine as well.

Ports 11111 and 30000 are not in use, and changing the values just to be sure yields the same exception being thrown. So that doesn't seem to be the issue.

As I'm writing this I discovered the issue dotnet/orleans#4524 pointing towards Hyper-V being the potential culprit. Changing the code to the following gets the silo up and running:
```
.ConfigureEndpoints(11111, 30000, listenOnAnyHostAddress: true);
```

Thanks for the support!
