### ISSUE TITLE
Webapp stuck in a black screen due to Orleans client

### ISSUE THREAD

**Issue by regul4rj0hn** [Maarten88/rrod#14]
First of all thanks for this great project. I figure that this is something I'm doing incorrectly, or something to do with my local machine. I really liked your project and was trying to get it to run but I am stuck on an error that leads to the site not displaying on the browser (black page).

I believe that I followed your instructions correctly. I'm on Windows 10 Pro running VS Pro as well. Azure Compute Emulator is installed and status reported running. I ran the Orleans project that has the following output which looks correct to me:

```
warn: Orleans.Runtime.NoOpHostEnvironmentStatistics[100708]
      No implementation of IHostEnvironmentStatistics was found. Load shedding will not work yet
Silo starting...
warn: Orleans.Runtime.Scheduler *stg/15/0000000f.WorkItemGroup[101215]
      Task [Id=115, Status=RanToCompletion] in WorkGroup [SystemTarget: S169.254.23.149:11111:269795451*stg/15/0000000f@S0000000f] took elapsed time 0:00:00.265158 for execution, which is longer than 00:00:00.2000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/System.5, ManagedThreadId=11, Executing Task Id=115 Status=RanToCompletion for 00:00:00.2694900 on WorkItem=System*WorkItemGroup:Name=*stg/15/0000000f,WorkGroupStatus=Running Executing for 00:00:00.2704802. .>
warn: Orleans.Runtime.MembershipService.MembershipOracleData[100619]
      Detected older version of myself - Marking other older clone as Dead -- Current Me=S169.254.23.149:11111:269795451 Older Me=S169.254.23.149:11111:269794538, Old entry= SiloAddress=S169.254.23.149:11111:269794538 SiloName=Silo_e44fa Status=Active
warn: Orleans.Runtime.Scheduler.WorkItemGroup[101215]
      Task [Id=2327, Status=RanToCompletion] in WorkGroup [LowPrioritySystemTarget: S169.254.23.149:11111:269795451*stg/0/00000000@S00000000] took elapsed time 0:00:00.3239865 for execution, which is longer than 00:00:00.2000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/3, ManagedThreadId=15, Executing Task Id=2327 Status=RanToCompletion for 00:00:00.3240319 on WorkItem=System*WorkItemGroup:Name=*stg/0/00000000,WorkGroupStatus=Running Executing for 00:00:00.3240356. .>
Silo started
warn: Orleans.Runtime.Scheduler.WorkItemGroup[101215]
      Task [Id=29753, Status=RanToCompletion] in WorkGroup [LowPrioritySystemTarget: S169.254.23.149:11111:269795451*stg/16570737466226579113/14b116a9@S14b116a9] took elapsed time 0:00:00.2406182 for execution, which is longer than 00:00:00.2000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/2, ManagedThreadId=14, Executing Task Id=29753 Status=RanToCompletion for 00:00:00.2406636 on WorkItem=System*WorkItemGroup:Name=*stg/16570737466226579113/14b116a9,WorkGroupStatus=Running Executing for 00:00:00.2407063. .>
```
Following that, I've run the Webapp project (previously npm install for node dependencies). It seems that it spends the seven attempts to create the Orleans client and connect and then fails with the following message:

```
Orleans.Runtime.SiloUnavailableException: 'The target silo became unavailable for message: Request *cli/5db875b2@3e52c293->S169.254.23.149:30000:269795451*stg/17/00000011@S00000011 #9: . Target History is: <S169.254.23.149:30000:269795451:*stg/17/00000011:@S00000011>. See https://aka.ms/orleans-troubleshooting for troubleshooting help.'
```
Some additional logs from the console output:

```
Orleans.OutsideRuntimeClient:Information: OutsideRuntimeClient.ConstructorReset(): client Id *cli/5db875b2
Exception thrown: 'Orleans.Runtime.SiloUnavailableException' in System.Private.CoreLib.dll
An unhandled exception of type 'Orleans.Runtime.SiloUnavailableException' occurred in System.Private.CoreLib.dll
The target silo became unavailable for message: Request *cli/5db875b2@3e52c293->S169.254.23.149:30000:269795451*stg/17/00000011@S00000011 #9: . Target History is: <S169.254.23.149:30000:269795451:*stg/17/00000011:@S00000011>. See https://aka.ms/orleans-troubleshooting for troubleshooting help.

The thread 0x4c64 has exited with code 0 (0x0).
The thread 0x4b3c has exited with code 0 (0x0).
The thread 0x780 has exited with code 0 (0x0).
The thread 0x2a84 has exited with code 0 (0x0).
The thread 0x8d0 has exited with code 0 (0x0).
The thread 0x52a0 has exited with code 0 (0x0).
The thread 0x4554 has exited with code 0 (0x0).
The thread 0x24a4 has exited with code 0 (0x0).
The thread 0x4938 has exited with code 0 (0x0).
The thread 0x380c has exited with code 0 (0x0).
Orleans.Runtime.Watchdog:Warning: .NET Runtime Platform stalled for 00:04:47.0377451 - possibly GC? We are now using total of 17MB memory. gc=10, 3, 2
The thread 0xc94 has exited with code 0 (0x0).
The thread 0x4f04 has exited with code 0 (0x0).
The thread 0x32a0 has exited with code 0 (0x0).
The thread 0x3ff8 has exited with code 0 (0x0).
The thread 0x4670 has exited with code 0 (0x0).
The thread 0x4de8 has exited with code 0 (0x0).
The thread 0x48b8 has exited with code 0 (0x0).
The thread 0x5220 has exited with code 0 (0x0).
The thread 0x4648 has exited with code 0 (0x0).
Orleans.Messaging.ClientMessageCenter:Error: Unexpected error getting an inbound message

System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection`1.TryTake(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Collections.Concurrent.BlockingCollection`1.Take()
   at Orleans.Messaging.ClientMessageCenter.WaitMessage(Categories type, CancellationToken ct) in D:\build\agent\_work\18\s\src\Orleans.Core\Messaging\ClientMessageCenter.cs:line 335
The thread 0x2d44 has exited with code 0 (0x0).
The thread 0x4c38 has exited with code 0 (0x0).
Orleans.Runtime.GrainTimer:Warning: -GrainTimer.Membership.ProbeTimer. TimerCallbackHandler:Orleans.Runtime.GrainTimer+<>c__DisplayClass16_0->System.Threading.Tasks.Task <FromTimerCallback>b__0(System.Object) did not fire on time. Last fired at 2018-07-20 15:13:06.605 GMT, 00:04:50.6394494 since previous fire, should have fired after 00:00:10.
Orleans.Runtime.GrainTimer:Error: Watchdog Freeze Alert: Orleans.Runtime.asynTask.SafeTimerBase.Membership.ReadTableTimer did not fire on time. Last fired at 2018-07-20 15:12:31.041 GMT, 00:05:26.2050718 since previous fire, should have fired after 00:01:00.
Orleans.Runtime.GrainTimer:Warning: -GrainTimer.Membership.ReadTableTimer. TimerCallbackHandler:Orleans.Runtime.GrainTimer+<>c__DisplayClass16_0->System.Threading.Tasks.Task <FromTimerCallback>b__0(System.Object) did not fire on time. Last fired at 2018-07-20 15:12:31.041 GMT, 00:05:26.2147821 since previous fire, should have fired after 00:01:00.
Orleans.Runtime.GrainTimer:Error: Watchdog Freeze Alert: Orleans.Runtime.asynTask.SafeTimerBase.Membership.ProbeTimer did not fire on time. Last fired at 2018-07-20 15:13:06.605 GMT, 00:04:50.6518612 since previous fire, should have fired after 00:00:10.
Orleans.Runtime.GrainTimer:Error: Watchdog Freeze Alert: Orleans.Runtime.asynTask.SafeTimerBase.Membership.IAmAliveTimer did not fire on time. Last fired at 2018-07-20 15:10:57.371 GMT, 00:06:59.9056191 since previous fire, should have fired after 00:05:00.
The program '[19540] dotnet.exe' has exited with code 0 (0x0).
Orleans.Runtime.Watchdog:Warning: Watchdog had 1 Health Check Failure(s) out of 2 Health Check Participants.
Orleans.Runtime.GrainTimer:Warning: -GrainTimer.Membership.IAmAliveTimer. TimerCallbackHandler:Orleans.Runtime.GrainTimer+<>c__DisplayClass16_0->System.Threading.Tasks.Task <FromTimerCallback>b__0(System.Object) did not fire on time. Last fired at 2018-07-20 15:10:57.371 GMT, 00:06:59.9171037 since previous fire, should have fired after 00:05:00.
Orleans.Runtime.Scheduler.WorkItemGroup:Warning: Task [Id=229785, Status=RanToCompletion] in WorkGroup [LowPrioritySystemTarget: S169.254.23.149:11111:269795451*stg/16570737466226579113/14b116a9@S14b116a9] took elapsed time 0:00:00.2081952 for execution, which is longer than 00:00:00.2000000. Running on thread <Runtime.Scheduler.WorkerPoolThread/3, ManagedThreadId=15, Executing Task Id=229785 Status=RanToCompletion for 00:00:00.2082481 on WorkItem=System*WorkItemGroup:Name=*stg/16570737466226579113/14b116a9,WorkGroupStatus=Running Executing for 00:00:00.2082857. .>
The program '[15664] dotnet.exe' has exited with code -1 (0xffffffff).
```
Maybe you've run into this in the past and can shed some light on this. I've got experience with asp.net core and react/redux but not with orleans. Thanks in advance.

**Comment by Maarten88** [comment]
It seems the silo starts correctly but the client somehow can't connect.
I don't know why this is happening for you and can't test for possible causes because I'm on vacation without my laptop, and won't be back soon 😀...

Maybe you can test a barebones Orleans sample project first. If it works retry rrod, check for differences in the startup configuration.
