### ISSUE TITLE
Unhandled exception when

### ISSUE THREAD

**Issue by Xuntar** [Maarten88/rrod#5]
Hi, thanks for this interesting project. I'm afraid I can't seem to get it to work though. I get the following error after running the application:
```
An unhandled exception occurred while processing the request.

NodeInvocationException: Prerendering failed because of error: An unhandled exception occurred while processing the request.

NodeInvocationException: Prerendering failed because of error: C:\Users\...\src\Webapp\ClientApp\dist\main-server.js:2251
return (async () => {
^
SyntaxError: Unexpected token (
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:542:28)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at findBootModule (C:\Users\...\AppData\Local\Temp\m0y3ntco.ru5:111:17)
Current directory is: C:\Users\...\src\Webapp
```

Running webpack for the Webapp doesn't throw any errors though.

**Comment by Xuntar** [comment]
I am terribly sorry to have bothered you, seems like it was just a matter of not having the right nodejs/npm version. It's working now with node v8.6.0 and npm 5.4.2.

**Comment by Maarten88** [comment]
No problem, I've added a remark in the README to make this requirement clear.
